name: "House"
description: " "
#url: "www.cyberrneticjello.com"
url: "http://localhost:4000"
destination: ../jcecil.github.io

paginate: 3
paginate_path: "/blog/page:num/"

#markdown: rdiscount
excerpt_separator: <!--more-->

permalink: /blog/:month-:day-:year/:title.html

highlighter: true


category-list: [steambox, mediacenter, javascript, website]
tag-list: [steambox, mediacenter, javascript, website]
