gems: 

name: "jcecil"
description: "A place for me to put all my derps"
url: "http://localhost:4000"
destination: ../jcecil.github.io

excerpt_separator: <!--more-->

permalink: /blog/:month-:day-:year/:title.html

highlighter: true

category-list: [steambox, mediacenter, javascript, website]
tag-list: [steambox, mediacenter, javascript, website]
