gems: 

name: "jcecil i/o"
description: "A place for me to put my everything"
url: "http://localhost:4000"
destination: ../build

excerpt_separator: <!--more-->

permalink: /blog/:month-:day-:year/:title.html

highlighter: true

category-list: [steambox, mediacenter, javascript, website, projects, raspi, rccar]
tag-list: [steambox, mediacenter, javascript, website]
